# Generated by Django 4.1.3 on 2022-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/cover_photos"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(2, "Customer"), (1, "Vendor")], null=True
            ),
        ),
    ]
