# Generated by Django 4.1.3 on 2022-11-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_role"),
        (
            "accounts",
            "0007_userprofile_cover_photo_userprofile_profile_picture_and_more",
        ),
    ]

    operations = []
